name: Release

on:
  workflow_dispatch:
  # push:
  #   tags:
  #     - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        arch: [arm64, amd64]
        exclude:
          - os: windows-latest
            arch: arm64
          - os: macos-latest
            arch: amd64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.20'

      - name: Build
        run: |
          make build

      - name: Rename binary for non-windows platforms
        if: matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest'
        run: |
          mkdir -p dist
          if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            mv ./build/mcp_start ./dist/mcp-start-darwin-${{ matrix.arch }}
          elif [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            mv ./build/mcp_start ./dist/mcp-start-linux-${{ matrix.arch }}
          else
            echo "Unsupported platform: ${{ matrix.os }}"
            exit 1
          fi

      - name: Rename binary for windows platforms
        if: matrix.os == 'windows-latest'
        run: |
          mkdir -p dist
          mv ./build/mcp_start.exe ./dist/mcp-start-windows-${{ matrix.arch }}.exe

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: release-binaries-${{ matrix.os }}-${{ matrix.arch }}-${{ github.run_id }}
          path: dist
          overwrite: true

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: release-binaries-*
          path: dist
          merge-multiple: true
      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/*
